//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LisansTalep", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LisansTalep : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LisansCevap", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LisansCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DogrulamaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DogrulamaKodu {
            get {
                return this.DogrulamaKoduField;
            }
            set {
                if ((this.DogrulamaKoduField.Equals(value) != true)) {
                    this.DogrulamaKoduField = value;
                    this.RaisePropertyChanged("DogrulamaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.LisansSoap")]
    public interface LisansSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki talep öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LisansDogrulama", ReplyAction="*")]
        WpfApp4.ServiceReference2.LisansDogrulamaResponse LisansDogrulama(WpfApp4.ServiceReference2.LisansDogrulamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LisansDogrulama", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp4.ServiceReference2.LisansDogrulamaResponse> LisansDogrulamaAsync(WpfApp4.ServiceReference2.LisansDogrulamaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LisansDogrulamaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LisansDogrulama", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp4.ServiceReference2.LisansDogrulamaRequestBody Body;
        
        public LisansDogrulamaRequest() {
        }
        
        public LisansDogrulamaRequest(WpfApp4.ServiceReference2.LisansDogrulamaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LisansDogrulamaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp4.ServiceReference2.LisansTalep talep;
        
        public LisansDogrulamaRequestBody() {
        }
        
        public LisansDogrulamaRequestBody(WpfApp4.ServiceReference2.LisansTalep talep) {
            this.talep = talep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LisansDogrulamaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LisansDogrulamaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp4.ServiceReference2.LisansDogrulamaResponseBody Body;
        
        public LisansDogrulamaResponse() {
        }
        
        public LisansDogrulamaResponse(WpfApp4.ServiceReference2.LisansDogrulamaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LisansDogrulamaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp4.ServiceReference2.LisansCevap LisansDogrulamaResult;
        
        public LisansDogrulamaResponseBody() {
        }
        
        public LisansDogrulamaResponseBody(WpfApp4.ServiceReference2.LisansCevap LisansDogrulamaResult) {
            this.LisansDogrulamaResult = LisansDogrulamaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LisansSoapChannel : WpfApp4.ServiceReference2.LisansSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LisansSoapClient : System.ServiceModel.ClientBase<WpfApp4.ServiceReference2.LisansSoap>, WpfApp4.ServiceReference2.LisansSoap {
        
        public LisansSoapClient() {
        }
        
        public LisansSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LisansSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisansSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisansSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp4.ServiceReference2.LisansDogrulamaResponse WpfApp4.ServiceReference2.LisansSoap.LisansDogrulama(WpfApp4.ServiceReference2.LisansDogrulamaRequest request) {
            return base.Channel.LisansDogrulama(request);
        }
        
        public WpfApp4.ServiceReference2.LisansCevap LisansDogrulama(WpfApp4.ServiceReference2.LisansTalep talep) {
            WpfApp4.ServiceReference2.LisansDogrulamaRequest inValue = new WpfApp4.ServiceReference2.LisansDogrulamaRequest();
            inValue.Body = new WpfApp4.ServiceReference2.LisansDogrulamaRequestBody();
            inValue.Body.talep = talep;
            WpfApp4.ServiceReference2.LisansDogrulamaResponse retVal = ((WpfApp4.ServiceReference2.LisansSoap)(this)).LisansDogrulama(inValue);
            return retVal.Body.LisansDogrulamaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp4.ServiceReference2.LisansDogrulamaResponse> WpfApp4.ServiceReference2.LisansSoap.LisansDogrulamaAsync(WpfApp4.ServiceReference2.LisansDogrulamaRequest request) {
            return base.Channel.LisansDogrulamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp4.ServiceReference2.LisansDogrulamaResponse> LisansDogrulamaAsync(WpfApp4.ServiceReference2.LisansTalep talep) {
            WpfApp4.ServiceReference2.LisansDogrulamaRequest inValue = new WpfApp4.ServiceReference2.LisansDogrulamaRequest();
            inValue.Body = new WpfApp4.ServiceReference2.LisansDogrulamaRequestBody();
            inValue.Body.talep = talep;
            return ((WpfApp4.ServiceReference2.LisansSoap)(this)).LisansDogrulamaAsync(inValue);
        }
    }
}
